### ISSUE TITLE
Padrões de Código

### ISSUE THREAD

**Issue by embs** [Bouckaert/donamaria#16]
## Diretrizes gerais:
* Largura máxima: 80 colunas;
* Código em inglês, comentários em português do Brasil;

## Referências:
* https://github.com/bbatsov/ruby-style-guide

**Comment by embs** [comment]
@isabarros @Bouckaert 

a gente pode adotar esse guia que tá na referência. O que acham?

**Comment by Bouckaert** [comment]
Apoiado, só assim eu paro de bagunçar!  :grimacing:
A instalação vira um card/branch ou podemos fazer dentro de algum outro?

**Comment by embs** [comment]
A ferramenta foi só uma ideia. Mas se formos adotá-la mesmo, acho que dá pra criar um card pra isso, né?

**Comment by isabarros** [comment]
Massa! Eu tava procurando um negócio desses. Vi os meninos do python usando um negócio equivante, não era uma gem obviamente (acho que era um plugin pro sublime, não lembro bem) mas era pra fazer exatamente isso que o cara fala (manter o código de acordo com certos padrões). E acho que a gente pode criar sim um card no trello pra instalação desse rubocop pra num misturar com outras coisas ;)

**Comment by isabarros** [comment]
E btw, acho que já podemos fechar essa issue aqui também, né? Criei o card no trello: https://trello.com/c/qRxL6OVL/23-instalar-a-gem-rubocop

**Comment by isabarros** [comment]
Só acho que essa issue aqui de padrões de código poderia ser fechada e as guidelines de padrões de código iriam pra outro lugar mais apropriado nos docs do repositório (pra ficar disponível pra qualquer um que for se aventurar no projeto), ai as anomalias a gente vai comentando direto nos commits, talvez seja mais eficiente assim. O que vocês acham?

**Comment by embs** [comment]
Pode ser.

Que tal uma seção no README com o link pra referência que tá na descrição desta issue? Daí depois a gente fecha.

**Comment by isabarros** [comment]
Beleza!

**Comment by Bouckaert** [comment]
:+1:

**Comment by embs** [comment]
Quem quiser se habilitar, fique à vontade! :grin: 

Aliás, precisamos escrever um README de fato (o que consta atualmente é apenas um dicionário de traduções). Acho que dá até pra criar um card relacionado a isso.

**Comment by isabarros** [comment]
Tem um card no baú de ideias pra isso já ;)

**Comment by embs** [comment]
Eita, é mesmo. [Link pro card](https://trello.com/c/LEzgBomm/16-melhorar-a-wiki-e-a-apresentacao-do-projeto-readme-github-pages).

**Comment by embs** [comment]
Criei uma [página na wiki](https://github.com/Bouckaert/donamaria/wiki/Padr%C3%B5es-de-C%C3%B3digo). Fechando este issue...
